### ISSUE TITLE
Dependency on tape is giving a warning

### ISSUE THREAD

**Issue by wqoq** [morganherlocker/bbox-intersect#1]
I installed `leaflet-bing-layer` which uses this package, and it gave me the following warning:
```
yarn : warning leaflet-bing-layer > bbox-intersect > tape > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

`tape` has been fixed as of version 4.6.1. Also, if it's just used for testing, shouldn't it be a devDependency instead?

**Comment by darcyparker** [comment]
https://github.com/morganherlocker/bbox-intersect/pull/2 addresses this.

**Comment by darcyparker** [comment]
FYI: #2 was merged. @morganherlocker - I am assuming you ran `npm publish` and we are waiting for the npm registry cache to update?  When the npm registry sees the new v0.1.2, this can probably be closed.
